# Generated by Django 3.2.12 on 2022-12-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdata',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
