# Generated by Django 3.2 on 2021-05-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0004_farmfollowers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
        ),
    ]
