# Generated by Django 3.2 on 2021-06-06 11:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapfarm', '0002_farmsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmmap',
            name='area',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='farmmap',
            name='farmBoundry',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='farmsegment',
            name='area',
            field=models.FloatField(default=0.0),
        ),
    ]
