# Generated by Django 3.2 on 2021-06-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapfarm', '0003_auto_20210606_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmmap',
            old_name='farmBoundry',
            new_name='farmBoundary',
        ),
    ]
