# Generated by Django 3.2.12 on 2022-11-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='startState',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_state', to='activity.state'),
        ),
    ]
