# Generated by Django 3.2.12 on 2022-08-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='title',
            field=models.CharField(default='New workflow', max_length=256),
        ),
    ]
