# Generated by Django 3.2.12 on 2022-08-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_workflow_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='currentState',
        ),
        migrations.AddField(
            model_name='workflow',
            name='currentStates',
            field=models.ManyToManyField(blank=True, null=True, related_name='current_state', to='activity.State'),
        ),
    ]
