# Generated by Django 3.2.12 on 2022-09-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20220831_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionapproval',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='completion_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
