# Generated by Django 3.2.12 on 2022-11-27 15:04

import activity.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_workflow_startstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionapproval',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='transitionapproval',
            name='reject',
        ),
        migrations.RemoveField(
            model_name='work',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='work',
            name='has_finished',
        ),
        migrations.RemoveField(
            model_name='work',
            name='is_halted',
        ),
        migrations.RemoveField(
            model_name='work',
            name='start_date',
        ),
        migrations.AddField(
            model_name='execution',
            name='jsonFlow',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExecutionWork',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.work')),
                ('completion_date', models.DateTimeField(blank=True, default=activity.models.return_date_time)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_finished', models.BooleanField(default=False)),
                ('is_halted', models.BooleanField(default=False)),
                ('associatedExecution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.execution')),
            ],
            bases=('activity.work',),
        ),
        migrations.CreateModel(
            name='ExecutionTransitionApproval',
            fields=[
                ('transitionapproval_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.transitionapproval')),
                ('approval', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('associatedExecution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.execution')),
            ],
            bases=('activity.transitionapproval',),
        ),
    ]
