# Generated by Django 3.2.12 on 2022-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20220923_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='currentStates',
            field=models.ManyToManyField(blank=True, related_name='current_state', to='activity.State'),
        ),
    ]
