# Generated by Django 3.2.12 on 2022-10-11 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0005_alter_workflow_currentstates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='assignee',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
