# Generated by Django 3.2.12 on 2022-10-15 17:21

import activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_work_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=activity.models.return_date_time),
        ),
    ]
