# Generated by Django 3.2.12 on 2022-12-04 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_workflowtrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=5)),
        ),
    ]
