# Generated by Django 3.2.12 on 2022-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_work_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonworkflow',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
