# Generated by Django 3.2.12 on 2022-11-08 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20221104_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New file', max_length=256)),
                ('file', models.FileField(upload_to='files')),
                ('associatedWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.work')),
            ],
        ),
    ]
