# Generated by Django 3.2 on 2021-10-27 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subscription',
        ),
        migrations.AddField(
            model_name='comments',
            name='pic',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
