# Generated by Django 3.2 on 2021-10-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='timestamp',
        ),
    ]
