# Generated by Django 3.2 on 2021-11-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211031_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
        migrations.CreateModel(
            name='PostPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='posts')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_picture', to='dashboard.post')),
            ],
        ),
        migrations.CreateModel(
            name='CommentPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='posts')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_picture', to='dashboard.comments')),
            ],
        ),
    ]
