# Generated by Django 3.2 on 2021-11-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_discussionboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discussion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.discussionboard'),
            preserve_default=False,
        ),
    ]
