# Generated by Django 3.2 on 2021-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_post_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpicture',
            name='pic',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
