# Generated by Django 3.2 on 2021-12-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_commentpicture_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpicture',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(),
        ),
    ]
