# Generated by Django 3.2.12 on 2022-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_farmgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
