# Generated by Django 3.2.12 on 2022-11-04 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0003_farm_archived'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='farm',
            unique_together={('user', 'name')},
        ),
    ]
