# Generated by Django 3.2.12 on 2022-12-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_farmgroups_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmgroups',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
