# Generated by Django 3.2 on 2022-03-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_completed',
            field=models.BooleanField(default=False),
        ),
    ]
