import datetime
AWS_ACCESS_KEY_ID="AKIAUVMTQ62STNS2BIOM"
AWS_SECRET_ACCESS_KEY="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"
AWS_FILE_EXPIRE=200
AWS_PRELOAD_METADATA=True
AWS_QUERYSTRING_AUTH=True
AWS_DEFAULT_ACL=None
DEFAULT_FILE_STORAGE='airfarms.aws.utils.MediaRootS3BotoStorage'
STATICFILES_STORAGE = 'airfarms.aws.utils.StaticRootS3BotoStorage'
AWS_STORAGE_BUCKET_NAME='servestaticfilebucket'
AWS_S3_REGION_NAME='ap-south-1'
AWS_S3_ADDRESSING_STYLE='virtual'
#AWS_S3_SIGNATURE_VERSION='S3V4'