# Generated by Django 3.2 on 2022-03-06 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0014_auto_20211228_1838'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0008_auto_20220130_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('transition_date', models.DateTimeField(blank=True)),
                ('notifiers', models.ManyToManyField(blank=True, related_name='state_notifiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_finished', models.BooleanField(default=False)),
                ('is_production', models.BooleanField(default=False)),
                ('currentState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_state', to='workflow.state')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('discussionboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.discussionboard')),
                ('notes', models.TextField(blank=True)),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_finished', models.BooleanField(default=False)),
                ('is_halted', models.BooleanField(default=False)),
                ('assignee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('associatedState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.state')),
                ('notifiers', models.ManyToManyField(blank=True, related_name='work_notifiers', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('dashboard.discussionboard',),
        ),
        migrations.CreateModel(
            name='TransitionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transitionToApprove', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.transition')),
            ],
        ),
        migrations.AddField(
            model_name='transition',
            name='associatedFlow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflow'),
        ),
        migrations.AddField(
            model_name='transition',
            name='next',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_state', to='workflow.state'),
        ),
        migrations.AddField(
            model_name='transition',
            name='previous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_state', to='workflow.state'),
        ),
    ]
