# Generated by Django 3.2 on 2022-03-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='title',
            field=models.CharField(default='New state', max_length=256),
        ),
    ]
