# Generated by Django 3.2 on 2022-03-09 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_state_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='currentState',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_state', to='workflow.state'),
        ),
    ]
