# Generated by Django 3.2.12 on 2022-04-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_alter_subscription_subscription_cost_currency'),
        ('workflow', '0005_auto_20220310_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonFlow', models.JSONField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflow')),
            ],
        ),
    ]
