# Generated by Django 3.2 on 2022-01-30 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20211228_1838'),
        ('farms', '0006_alter_farm_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmDiscussionBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussionBoard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.discussionboard')),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
        ),
    ]
