# Generated by Django 3.2 on 2022-01-30 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20211228_1838'),
        ('farms', '0007_farmdiscussionboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmdiscussionboard',
            name='discussionBoard',
        ),
        migrations.RemoveField(
            model_name='farmdiscussionboard',
            name='id',
        ),
        migrations.AddField(
            model_name='farmdiscussionboard',
            name='discussionboard_ptr',
            field=models.OneToOneField(auto_created=True, default=6, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.discussionboard'),
            preserve_default=False,
        ),
    ]
